version: "3"

services:
  bot:
    build:
      context: ./
      dockerfile: ./apps/telegram-bot/Dockerfile
    env_file:
      - ./apps/telegram-bot/.env.local
    environment:
      - NODE_ENV=production
